disquaire_projet/urls.py
from django.conf import settings
from django.conf.urls import include,url
from django.contrib import admin
from store import views


urlpatterns = [
    url(r'^$', views.index),
    url(r'^store/',include('store.urls',namespace="store")),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
            url(r'^_debug_/', include(debug_toolbar.urls)),
            ] + urlpatterns

store/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
        url(r'^$',views.listing,name='listing'),
        url(r'^(?P<album_id>[0-9]+)/$',views.detail,name='detail'),
        url(r'^search/$',views.search,name='search'),
        ]

store/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here
class Artist(models.Model):
    name= models.CharField(max_length=200,unique=True)
    
    def __str__(self):
        return self.name

class Contact(models.Model):
    email=models.EmailField(max_length=100)
    name=models.CharField(max_length=200)

    def __str__(self):
        return self.name
    

class Album(models.Model):
    reference=models.IntegerField(null=True)
    created_at=models.DateTimeField(auto_now_add=True)
    available= models.BooleanField(default=True)
    title = models.CharField(max_length=200)
    picture= models.URLField()
    artists= models.ManyToManyField(Artist,related_name='albums',blank=True)

    def __str__(self):
        return self.title

class Booking(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    contacted= models.BooleanField(default=False)
    album=models.OneToOneField(Album)
    contact=models.ForeignKey(Contact, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.contact.name

store/store/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

store/store/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

store/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals


# Create your views here.
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import render
from .models import Album,Artist,Contact,Booking

def index(request):
    albums = Album.objects.filter(available=True).order_by('-created_at')[:12]
    context={ 'albums':albums}
    return render(request,'store/index.html',context)

def listing(request):
    albums= Album.objects.filter(available=True)
    context = {
            'albums' : albums
            }
    return render(request,'store/listing.html',context)

def detail(request, album_id):
    album=Album.objects.get(pk=album_id)
    artists = [artist.name for artist in album.artists.all()]
    artists_name= " ".join(artists) 
    context = { 
            'album_title' : album.title,
            'artists_name' : artists_name,
            'album_id' : album.id,
            'thumbnail' : album.picture
            }
    return render(request,'store/detail.html',context)

def search(request):
    query= request.GET.get('query')
    albums= Album.objects.all()
    print("type of albums = ",type(albums))
    if not query:
        albums = Album.objects.all()
    else:
        albums= Album.objects.filter(title__icontains=query)
    if not albums.exists(): 
        albums= Album.objects.filter(artists__name__icontains = query )
    title="Résultat pour la recherche %s" %query
    context = {
            'albums' : albums,
            'title' : title
            }
    return render(request,'store/search.html',context)

store/templates/store/base.html

Skip to content
Pull requests
Issues
Marketplace
Explore
@kutta75
Learn Git and GitHub without any code!

Using the Hello World guide, you’ll start a branch, write comments, and open a pull request.
oc-courses /
decouvrez_django

8
39

    77

Code
Issues 7
Pull requests 2
Actions
Projects
Wiki
Security

    Insights

decouvrez_django/disquaire_project/store/templates/store/base.html
@celine-m-s
celine-m-s Update base.html
Latest commit 787d7e1 on 22 Jan 2020
History
1 contributor
85 lines (73 sloc) 3.34 KB
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'store/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'store/css/business-casual.css' %}" />

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

    <div class="brand"><a href="/">Le bateau pirate</a></div>
    <div class="address-bar">Radio rock, Mer du nord (ou dans le 20e, à Paris)</div>

    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Menu</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                <a class="navbar-brand" href="index.html">Le bateau pirate</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
			    <a href="{% url 'store:listing' %} " >Tous nos disques</a>
                    </li>
                    <li>
                        <a href="#">A propos</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>


    <div class="container">
      <div class="row">
        <div class="box">
          {% block content %}{% endblock %}
        </div>
      </div>
    </div>


    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>Copyright &copy; <a href="http://bit.ly/36nxNJS" target="_blank">Céline Martinet Sanchez</a> pour <a href="https://openclassrooms.com" target="_blank">OpenClassrooms</a></p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="{% static 'store/js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'store/js/bootstrap.min.js' %}"></script>

  </body>
</html>

    © 2021 GitHub, Inc.
    Terms
    Privacy
    Security
    Status
    Docs

    Contact GitHub
    Pricing
    API
    Training
    Blog
    About


store/templates/store/detail.html
{% extends 'store/base.html' %}

{% block content %} 
<h2> dans detail.html  </h2>

<h1 class ="intro-text text-center" > {{ album_title }} </h1> 
<hr class = "detail-separator"> 
<div class= "col-md-6"> 
	<img src="{{ thumbnail }}" alt="{{ album_title }}" class = "img-responsive"> 
</div> 
<div class = "col-md-6" > 
	<div style = "margin-botton:45px" > 
		<h2 class =  "text-center artist_name" > Artistes </h2> 
		<p> {{ artists_name }} </p> 
	</div> 
<h2 class= "text-center artist_name"> Réserver {{ album_title }} </h2>  
<p style = "margin-bottom: 20px;"> Demandez nous de mettre de coté {{ album_title }} et venez le chercher fissa </p> 
<form class= "form-inline" action ="/" method = "post" > 
	<div class = "form-group" > 
		<label for ="name" class="control-label" > Nom </label> 
		<input type= "text" name = "name" value="" id="name"> 
	</div> 
	<div class= form-group > 
		<label for"email" class = "control-label">  E-Mail </label> 
		<input type="text" name=email value="" id="email">
	</div> 
	<!-- <input type="hidden" class="hidden" value="" name="album_id"> -->
	<button type="submit" class="btn btn-success"> réserver </button> 
</form> 

{% endblock content %}

store/templates/store/index.html
{% extends 'store/base.html' %}
{% block content %}
je me suis faufilé dans le gabarit parent : salut !!! 
{% include 'store/list.html' with list_title=title %}
{% endblock %}

store/templates/store/list.html
je viens depuis le fichier list.html
<div class="col-lg-12">
<hr>
<h2 class="intro-text text-center"> {{ list_title}}
</h2>
</div>
{% if albums|length_is:"0" %}
	<div class="text-center" >
		Aucun album trouvé 
	</div>
	{% else %}

	{% for album in albums %}
	<div class="col-sm-4 text-center">
		<a href="{% url 'store:detail' album_id=album.id %}">
			<img class="img-responsive" src="{{ album.picture }}" alt="{{ album.title }}">
		</a>
			<h3> <a href="/"> {{ album.title }} </a> </h3> 
			{% for artist in album.artists.all %}
				<p> {{ artist.name }} </p>
			{% endfor %} 
	</div> 
	{% if forloop.counter|divisibleby:3 %} <div> {% endif %}
	{% endfor %}
{% endif %}

store/templates/store/listing.html
{% extends 'store/base.html' %}

{% block content %}

	{% include 'store/list.html' with list_title='Tous nos disques' %}


{% endblock %}

store/templates/store/search.html
{% extends 'store/base.html' %}
{% block content %}
	{% include 'store/list.html' with list_title=title %}

{% endblock %}